#!/usr/bin/env bash
set -euo pipefail

SCRIPT="/data/.openclaw/workspace/security-review.sh"
REPORT_DIR="/data/.openclaw/workspace/memory/security"
REPORT="$REPORT_DIR/latest_review.md"

# Check script exists and is executable
if [ ! -x "$SCRIPT" ]; then
  echo "FAIL: security-review.sh not found or not executable"
  exit 1
fi

# Run the security review (commented out for CI - uncomment to run full test)
# bash "$SCRIPT"

# For CI, just verify the script is valid bash
if ! bash -n "$SCRIPT"; then
  echo "FAIL: security-review.sh has syntax errors"
  exit 1
fi

# Check report directory exists
if [ ! -d "$REPORT_DIR" ]; then
  echo "FAIL: security report directory not found"
  exit 1
fi

# Check for any recent security reports
recent_reports=$(ls "$REPORT_DIR"/20*-security-review.md 2>/dev/null | wc -l)
if [ "$recent_reports" -eq 0 ]; then
  echo "WARN: No security reports found in $REPORT_DIR"
  echo "Run 'bash security-review.sh' to generate a report"
  # Don't fail - reports are generated by cron
fi

echo "PASS: security-review.sh is valid and configured correctly"
