#!/usr/bin/env bash
# Shared lab-lane defaults. Source this file from lab wrapper scripts.
set -euo pipefail

LAB_PROJECT_DIR="/data/.openclaw/workspace/projects/mission-control-lab"
export MISSION_CONTROL_PREVIEW_RUNTIME_DIR="${MISSION_CONTROL_PREVIEW_RUNTIME_DIR:-$LAB_PROJECT_DIR/.lab-runtime}"
export MISSION_CONTROL_LAB_ENV_FILE="${MISSION_CONTROL_LAB_ENV_FILE:-$MISSION_CONTROL_PREVIEW_RUNTIME_DIR/mission-control-lab.env}"
export MISSION_CONTROL_PREVIEW_PORT="${MISSION_CONTROL_PREVIEW_PORT:-3015}"
export MISSION_CONTROL_PREVIEW_INTERNAL_HOST="${MISSION_CONTROL_PREVIEW_INTERNAL_HOST:-127.0.0.1}"
export MISSION_CONTROL_PREVIEW_INTERNAL_PORT="${MISSION_CONTROL_PREVIEW_INTERNAL_PORT:-3017}"
export MISSION_CONTROL_WS_SIDECAR_HOST="${MISSION_CONTROL_WS_SIDECAR_HOST:-127.0.0.1}"
export MISSION_CONTROL_WS_SIDECAR_PORT="${MISSION_CONTROL_WS_SIDECAR_PORT:-3016}"
export MISSION_CONTROL_WS_PUBLIC_PATH="${MISSION_CONTROL_WS_PUBLIC_PATH:-/api/runtime-bridge/ws}"
export MISSION_CONTROL_WS_LIVE_PUBLIC_PATH="${MISSION_CONTROL_WS_LIVE_PUBLIC_PATH:-/api/runtime-bridge/live}"
export MISSION_CONTROL_WS_UPSTREAM_ORIGIN="${MISSION_CONTROL_WS_UPSTREAM_ORIGIN:-https://lab.motiondisplay.cloud}"
export MISSION_CONTROL_SERVER_CONNECT="${MISSION_CONTROL_SERVER_CONNECT:-1}"

export DEFEATBETA_SIDECAR_HOST="${DEFEATBETA_SIDECAR_HOST:-127.0.0.1}"
export DEFEATBETA_SIDECAR_PORT="${DEFEATBETA_SIDECAR_PORT:-8791}"
export DEFEATBETA_SIDECAR_URL="${DEFEATBETA_SIDECAR_URL:-http://${DEFEATBETA_SIDECAR_HOST}:${DEFEATBETA_SIDECAR_PORT}}"
