import type { WatchlistItem } from '@/lib/convex/watchlist-api';

export const sampleWatchlistItems: WatchlistItem[] = [
  {
    _id: 'sample-msft',
    userKey: 'sample',
    watchlistId: 'sample-main',
    symbol: 'MSFT.US',
    displaySymbol: 'MSFT',
    name: 'Microsoft',
    exchange: 'NASDAQ',
    currency: 'USD',
    tags: ['Compounder', 'AI infra'],
    thesis: 'Software durability plus cloud and AI infrastructure demand. Watch valuation after earnings resets.',
    priority: 'core',
    alertLevel: 'watch',
    sortOrder: 1000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
  },
  {
    _id: 'sample-asml',
    userKey: 'sample',
    watchlistId: 'sample-main',
    symbol: 'ASML.AS',
    displaySymbol: 'ASML.AS',
    name: 'ASML Holding',
    exchange: 'Euronext Amsterdam',
    currency: 'EUR',
    tags: ['Semis', 'Europe'],
    thesis: 'High-quality lithography monopoly. Good candidate when cyclicality gives a better entry.',
    priority: 'radar',
    alertLevel: 'watch',
    sortOrder: 2000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
  },
  {
    _id: 'sample-005930',
    userKey: 'sample',
    watchlistId: 'sample-main',
    symbol: '005930.KS',
    displaySymbol: '005930.KS',
    name: 'Samsung Electronics',
    exchange: 'KRX',
    currency: 'KRW',
    tags: ['Memory', 'Korea'],
    thesis: 'Memory-cycle recovery candidate. Needs margin confirmation and cleaner AI memory read-through.',
    priority: 'radar',
    alertLevel: 'none',
    sortOrder: 3000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
  },
  {
    _id: 'sample-wawi',
    userKey: 'sample',
    watchlistId: 'sample-cyclicals',
    symbol: 'WAWI.OL',
    displaySymbol: 'WAWI.OL',
    name: 'Wallenius Wilhelmsen',
    exchange: 'Oslo Børs',
    currency: 'NOK',
    tags: ['Shipping', 'Cyclical'],
    thesis: 'Interesting cash-generation profile, but keep it clearly separated from compounder bucket.',
    priority: 'speculative',
    alertLevel: 'none',
    sortOrder: 4000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
  },
];


export const sampleWatchlists = [
  {
    _id: 'sample-main',
    userKey: 'sample',
    name: 'Main Watchlist',
    description: 'Core research queue for quality names and active ticker work.',
    pinned: true,
    sortOrder: 1000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
    items: sampleWatchlistItems.filter((item) => item.watchlistId === 'sample-main'),
  },
  {
    _id: 'sample-cyclicals',
    userKey: 'sample',
    name: 'Cyclicals Radar',
    description: 'Names that need stricter timing and cycle awareness.',
    pinned: false,
    sortOrder: 2000,
    createdAt: Date.parse('2026-05-01T08:00:00Z'),
    updatedAt: Date.parse('2026-05-02T04:00:00Z'),
    items: sampleWatchlistItems.filter((item) => item.watchlistId === 'sample-cyclicals'),
  },
];
